contact_links:
  - name: Mod Support
    url: https://discord.gg/yjGFsUD
    about: Please ask and answer questions about mods here.
  - name: Goose Support for Windows
    url: https://discord.gg/GVTtAPC
    about: Do you have support questions about Goose? Please ask here.
